### ISSUE TITLE
An endless loop in AdminPage

### ISSUE THREAD

**Issue by besLisbeth** [geocine/react-auth-demo#1]
So, as I told you earlier, an issue was not in the AlertRef.

First of all, the problem is that for the component `AdminPage` you chose function component with the server request which started as soon as component created. 
Once you rewrite your component to class with the request in `componentDidMount` body - everything starts to work nice.

e.g.
```
export default class AdminPage extends Component {

    constructor(props) {
        super(props);
    }

    componentDidMount(){
        getHttp('/users')
            .then(() => {
                console.log('oops')
            }, error => console.log(error.status))
            .catch(err => {
                console.log(err)
            })
    }

    render() {
        return (
            <div>
                <h2> Admin </h2>
                <p>
                    Welcome to the Admin Page.
                </p>
            </div>
        )
    }
}
```

Another thing is that you have a mistake in catching server errors. I hope, that you've noticed that you have 404 error, you throw your custom error from `checkStatus` function, but instead catching it in `AdminPage` component it goes to `then` in `getHttp` method.  That happened because all errors from the server requests go to the second argument in promise's `then` method, and all errors which happened in component itself go to the `catch` method. That's why you never had `err.status` console logged.
For further information about how to get it right I'm attaching a couple of resources:
1. https://twitter.com/dan_abramov/status/776891811222675457?lang=en
2. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#Syntax

In my example, I also used the second `then` promise argument.

Hope that will help you!

**Comment by geocine** [comment]
@besLisbeth , thanks for all your help , I have purposely added catch on the `getHttp` just to tes. I will be adding it inside `checkStatus` before throwing the error.  

It's interesting to know that a function component behaves that way compared to the class. I will test this out later :+1:
